### ISSUE TITLE
consider throwing an Error instance

### ISSUE THREAD

**Issue by cdaringe** [alexbbt/read-last-lines#6]
https://github.com/alexbbt/read-last-lines/blob/master/index.js#L31

vs a raw string.  throwing an `Error` is more conventional, works w/ `instanceof` checks when sniffing for errors, gives a stack, etc etc. ex:

```js
> throw 'err'
err
> throw new Error('err')
Error: err
    at repl:1:7
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:340:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:537:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:189:7)
    at REPLServer.Interface._onLine (readline.js:238:10)
    at REPLServer.Interface._line (readline.js:582:8)
>
```

**Comment by alexbbt** [comment]
Thanks for pointing that out, it should be fixed now
